- name: Install InfluxDB
  yum: 
  	name: "{{ file_server }}/influxdb_{{ influxdb_version }}_amd64.rpm"
  	state: installed
  	disable_gpg_check: yes
  become: yes
  notify:
    - start influxdb

- name: Install Kapacitor
  yum: 
    name: "{{ file_server }}/kapacitor_{{ kapacitor_version }}_amd64.rpm"
    state: installed
    disable_gpg_check: yes
  become: yes
  notify:
    - start kapacitor

- name: Install Telegraf
  yum: 
    name: "{{ file_server }}/telegraf_{{ telegraf_version }}_amd64.rpm"
    state: installed
    disable_gpg_check: yes
  become: yes
  notify:
    - start telegraf

- name: Install Chronograf
  yum: 
    name: "{{ file_server }}/chronograf_{{ chronograf_version }}_amd64.rpm"
    state: installed
    disable_gpg_check: yes
  become: yes
  notify:
    - start chronograf
