- name: start influxdb
  service: name=influxdb state=restarted
  become: yes

- name: start kapacitor
  service: name=kapacitor state=restarted
  become: yes

- name: start telegraf
  service: name=telegraf state=restarted
  become: yes

- name: start chronograf
  service: name=chronograf state=restarted
  become: yes
